### ISSUE TITLE
Add fail sounds

### ISSUE THREAD

**Issue by idjotherwise** [theogf/Ding.jl#2]
Would be great if there was functionality to play a "fail" sound when an error is thrown. Could either be its own `@problem` macro, or you could check the status of the result in https://github.com/theogf/Ding.jl/blob/main/src/ding.jl#L4 and then choose the sound from some `Ding.fail_sounds` collection

**Comment by theogf** [comment]
Implemented with `@ohno` and `ohno_repl` :D
